import type { DayReport, Technician } from "@/lib/types";

const shopId = "dayton" as const;
const day = "2026-10-02";

function tech(
  id: string,
  name: string,
  clockedHours: number,
  soHours: number,
  sheetLine?: string,
  sheetNote?: string,
): Technician {
  return { id, shopId, name, clockedHours, soHours, sheetLine, sheetNote };
}

function asIs(
  id: string,
  techId: string,
  start: string,
  end: string,
  detail: string,
  suggested: string,
  notAGap = false,
): DayReport["findings"][number] {
  return {
    id,
    day,
    shopId,
    techId,
    kind: "as_is",
    start,
    end,
    minutes: 0,
    detail,
    suggested,
    notAGap,
    recommendation: null,
  };
}

/**
 * Friday, October 2, 2026, Dayton.
 * Saturday, October 3 is a reviewable day with no report loaded yet.
 * Covington, Greenville, Springfield, and Mobile have no rows until a report is added.
 */
export const SEED: DayReport[] = [
  {
    day,
    shopId,
    technicians: [
      tech("nick-sontag", "Nick Sontag", 6.54, 6.52),
      tech("brayden-mapp", "Brayden Mapp", 9.95, 9.89),
      tech("colby-purvis", "Colby Purvis", 8.99, 8.99),
      tech(
        "zach-spencer",
        "Zach Spencer",
        9.89,
        7.24,
        "73.2% now (7.24 SO / 9.89 clocked). About 100% if the edits are made.",
        "Needs about 2 hours 27 minutes. The three D-88889 extensions plus a new tire service order cover it.",
      ),
      tech(
        "cole-lozan",
        "Cole Lozan",
        8.83,
        8.14,
        "92.2% now (8.14 SO / 8.83 clocked). About 98.9% with the Nick edit; about 99.8% if the 5 minutes is closed too.",
        "Needs about 31 minutes. The “Help Nick” block is enough on its own.",
      ),
      tech(
        "tanveer-dhaliwal",
        "Tanveer Dhaliwal",
        4.0,
        3.73,
        "93.2% now (3.73 SO / 4.00 clocked). About 99.5% if both gaps are closed.",
        "Needs about 11 minutes. The 9-minute “shop help” alone is not enough (that only gets him to about 97%). Close both.",
      ),
    ],
    orders: [
      { id: "D-88889", shopId, title: "Replace engine", status: "priorities" },
      { id: "D-89637", shopId, title: "Replace injectors", status: "office" },
      { id: "D-90318", shopId, title: "Replace and program CECU", status: "priorities" },
      { id: "D-90552", shopId, title: "", status: "invoiced" },
      { id: "D-90301", shopId, title: "", status: "invoiced" },
      { id: "D-90394", shopId, title: "", status: "priorities" },
      { id: "D-90523", shopId, title: "", status: "priorities" },
    ],
    findings: [
      {
        id: "zach-0629",
        day,
        shopId,
        techId: "zach-spencer",
        kind: "gap",
        start: "06:29",
        end: "08:07",
        minutes: 97,
        detail: "Clocked in. No job until 8:07.",
        recommendation: {
          orderId: "D-88889",
          work: "Replace engine",
          start: "06:29",
          end: "08:07",
          minutes: 97,
          summary: "Start D-88889 Replace engine at 6:29 (clock-in) instead of 8:07.",
        },
      },
      asIs("zach-0807", "zach-spencer", "08:07", "11:06", "D-88889 / Replace engine.", "Leave as is."),
      asIs(
        "zach-1106",
        "zach-spencer",
        "11:06",
        "12:07",
        "D-90552 / Install customer supplied…, with a few seconds hopping to “Unit info needed” and back. Not a real gap.",
        "Leave the hops. Do not chase the few seconds.",
      ),
      {
        id: "zach-1207",
        day,
        shopId,
        techId: "zach-spencer",
        kind: "gap",
        start: "12:07",
        end: "12:20",
        minutes: 13,
        detail: "Off D-90552, not on a job, then back to D-88889 at 12:20.",
        recommendation: {
          orderId: "D-88889",
          work: "Replace engine",
          start: "12:07",
          end: "12:20",
          minutes: 13,
          summary: "Start that D-88889 segment at 12:07 instead of 12:20.",
        },
      },
      asIs("zach-1220", "zach-spencer", "12:20", "13:09", "D-88889 / Replace engine. Clocked out at 1:09.", "Leave as is."),
      {
        id: "zach-off-1309",
        day,
        shopId,
        techId: "zach-spencer",
        kind: "off_clock",
        start: "13:09",
        end: "13:44",
        minutes: 35,
        detail: "Off the clock.",
        suggested: "No edit.",
        recommendation: null,
      },
      {
        id: "zach-1344",
        day,
        shopId,
        techId: "zach-spencer",
        kind: "gap",
        start: "13:44",
        end: "13:47",
        minutes: 3,
        detail: "Clocked back in. No job until 1:47.",
        recommendation: {
          orderId: "D-88889",
          work: "Replace engine",
          start: "13:44",
          end: "13:47",
          minutes: 3,
          summary: "Start the afternoon D-88889 at 1:44 (clock-in).",
        },
      },
      asIs(
        "zach-1347",
        "zach-spencer",
        "13:47",
        "15:06",
        "D-88889 / Replace engine. Clocked out of the job at 3:06.",
        "Leave as is. Do not stretch this job across the tire.",
      ),
      {
        id: "zach-flag-1506",
        day,
        shopId,
        techId: "zach-spencer",
        kind: "flag",
        start: "15:06",
        end: "15:51",
        minutes: 45,
        detail: "Still clocked. Activity: Normal Non Pro. Comment: “plugging tire for mansfeild.” No service order.",
        suggested: "Do not put this on D-88889. Build a service order and invoice the customer for the tire plug. That 45 minutes becomes SO time.",
        recommendation: null,
      },
      asIs(
        "zach-1551",
        "zach-spencer",
        "15:51",
        "16:57",
        "Clocked, and the whole window is on D-88889 / Replace engine.",
        "Leave as is.",
      ),
      asIs("cole-0709", "cole-lozan", "07:09", "07:26", "D-90394 / Unit is in derate. Clocked window matches the job.", "Leave as is."),
      {
        id: "cole-0727",
        day,
        shopId,
        techId: "cole-lozan",
        kind: "gap",
        start: "07:27",
        end: "08:03",
        minutes: 35,
        detail:
          "Separate clock window. Activity: Normal Non Pro. Comment: “Help Nick.” No service order. Nick Sontag was on D-89637 Replace injectors this whole stretch (7:08–9:35).",
        recommendation: {
          orderId: "D-89637",
          work: "Replace injectors",
          start: "07:27",
          end: "08:03",
          minutes: 35,
          summary: "Put this time on D-89637 Replace injectors. This alone gets Cole to about 98.9%.",
        },
      },
      asIs(
        "cole-0803",
        "cole-lozan",
        "08:03",
        "09:23",
        "Back on D-90394 (derate, unit info, check-in inspection).",
        "Leave as is. A one-minute hop at 9:23 is not a real gap.",
      ),
      asIs(
        "cole-0924",
        "cole-lozan",
        "09:24",
        "11:40",
        "D-90301 / Customer would like… then “TPMS…” Clocked out at 11:40.",
        "Leave as is.",
      ),
      {
        id: "cole-off-1140",
        day,
        shopId,
        techId: "cole-lozan",
        kind: "off_clock",
        start: "11:40",
        end: "12:31",
        minutes: 51,
        detail: "Off the clock.",
        suggested: "No edit.",
        recommendation: null,
      },
      asIs("cole-1231", "cole-lozan", "12:31", "15:03", "Whole window on D-90301 / TPMS. Clocked out at 3:03.", "Leave as is."),
      {
        id: "cole-off-1503",
        day,
        shopId,
        techId: "cole-lozan",
        kind: "off_clock",
        start: "15:03",
        end: "15:10",
        minutes: 7,
        detail: "Off the clock.",
        suggested: "No edit.",
        recommendation: null,
      },
      asIs("cole-1510", "cole-lozan", "15:10", "15:18", "D-90301 / Check-in inspection.", "Leave as is."),
      {
        id: "cole-1518",
        day,
        shopId,
        techId: "cole-lozan",
        kind: "gap",
        start: "15:18",
        end: "15:22",
        minutes: 5,
        detail: "Between D-90301 and D-90318.",
        recommendation: {
          orderId: "D-90318",
          work: "Replace and program CECU",
          start: "15:18",
          end: "15:22",
          minutes: 5,
          summary: "Start D-90318 Replace and program CECU at 3:18 instead of 3:22.",
          optional: true,
        },
      },
      asIs("cole-1522", "cole-lozan", "15:22", "16:57", "D-90318 / Replace and program CECU through clock-out.", "Leave as is."),
      asIs(
        "tanveer-1259",
        "tanveer-dhaliwal",
        "12:59",
        "13:00",
        "Clocked for about a minute, then a new clock window.",
        "No edit.",
        true,
      ),
      {
        id: "tanveer-1300",
        day,
        shopId,
        techId: "tanveer-dhaliwal",
        kind: "gap",
        start: "13:00",
        end: "13:09",
        minutes: 9,
        detail: "Clocked. Activity: Normal Non Pro. Comment: “shop help.” No service order.",
        recommendation: {
          orderId: "D-89637",
          work: "Replace barometric pressure",
          start: "13:00",
          end: "13:09",
          minutes: 9,
          summary: "Start D-89637 Replace barometric pressure at 1:00 instead of 1:09.",
        },
      },
      asIs("tanveer-1309", "tanveer-dhaliwal", "13:09", "14:21", "D-89637 / Replace barometric pressure.", "Leave as is."),
      {
        id: "tanveer-1421",
        day,
        shopId,
        techId: "tanveer-dhaliwal",
        kind: "gap",
        start: "14:21",
        end: "14:27",
        minutes: 6,
        detail: "Off the job, then an 8-second punch back on D-89637, then onto D-90301 at 2:27.",
        recommendation: {
          orderId: "D-89637",
          work: "Replace barometric pressure",
          start: "14:21",
          end: "14:27",
          minutes: 6,
          summary: "Keep him on D-89637 until 2:27, when D-90301 starts.",
        },
      },
      asIs("tanveer-1427", "tanveer-dhaliwal", "14:27", "15:48", "D-90301 / Install customer supplied…", "Leave as is."),
      asIs("tanveer-1548", "tanveer-dhaliwal", "15:48", "16:59", "D-90523 / B service straight truck, through clock-out.", "Leave as is."),
    ],
  },
];
