AUTOS = [
  {
    "id": "monthly-fullbay-receipt-pdf-to-sheldon",
    "name": "Monthly Fullbay receipt PDF to Sheldon",
    "owner": "Grok Bot",
    "category": "Finance & Vendors",
    "does": "Finds the monthly Fullbay subscription receipt in Luke's Gmail (Trash included), builds a one-page PDF, sends it to Sheldon Lavy in Slack, and gives Luke a heads-up.",
    "trigger": "9:32 AM on the 5th–9th of each month",
    "trigger_type": "Schedule",
    "delivers_to": "Sheldon Lavy (Slack DM) + Luke (Grok Bot chat)",
    "last_run": None,
    "next_run": "Nov 5, 9:32 AM",
    "status": "active",
    "created": "Oct 9",
    "source": "Confirmed by Grok Bot, Oct 10",
  },
  {
    "id": "weekday-parts-research-daily-summary",
    "name": "Weekday parts research daily summary",
    "owner": "Ed",
    "category": "Parts & Purchasing",
    "does": "Wrap-up of the day's Fullbay parts research (in-house finds, transfers, orders, open Unknowns, accuracy misses scored by Chris), sent to Luke in Ed's chat. Stays quiet if nothing new.",
    "trigger": "Weekdays 5:22 PM",
    "trigger_type": "Schedule",
    "delivers_to": "Luke (Ed's chat)",
    "last_run": "Oct 9, 5:27 PM (nothing to send; the Oct 8 run failed and was sent by hand)",
    "next_run": "Mon Oct 12, 5:22 PM",
    "status": "active",
    "created": "~late Sep",
    "source": "Confirmed by Ed, Oct 10",
  },
  {
    "id": "daily-servco-inventory-pull",
    "name": "Daily Servco inventory pull",
    "owner": "2.0",
    "category": "Parts & Purchasing",
    "does": "Downloads the newest Inventory xlsx from Servco 2.0 Fullbay Files into the parts-research app data and keeps the last 7.",
    "flag": "Possible duplicate: Chris 4:58 and 2.0 4:59 both pull the inventory file",
    "trigger": "Weekdays 4:59 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Chris; Luke only if blocked",
    "last_run": "Oct 9, 5:03 AM",
    "next_run": "Oct 12, 4:59 AM",
    "status": "active",
    "created": "~Sep 28",
    "source": "Confirmed by 2.0, Oct 10",
  },
  {
    "id": "daily-parts-margin-report",
    "name": "Daily Parts Margin report",
    "owner": "2.0",
    "category": "Finance & Vendors",
    "does": "Dayton shop parts margin for yesterday, week to date, and month to date against a 35% target, from Servco 2.0.",
    "trigger": "Weekdays 8:05 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Slack group DM with Jared and Jeremy + copy to Luke",
    "last_run": "Oct 9, 8:23 AM",
    "next_run": "Oct 12, 8:05 AM",
    "status": "active",
    "created": "Sep 28",
    "source": "Confirmed by 2.0, Oct 10",
  },
  {
    "id": "new-qbo-vendors-slack-angie",
    "name": "New QBO vendors → Slack Angie",
    "owner": "Don",
    "category": "Finance & Vendors",
    "does": "Read-only check of QuickBooks Online for vendors created the prior day (Monday covers Fri–Sun). DMs Angie Geise as Luke with each new vendor, its transactions, and likely duplicates, then sends Luke a one-line note. Silent if there are none.",
    "trigger": "Weekdays 6:12 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Angie Geise (Slack DM as Luke) + one-line note to Luke (Don's chat)",
    "last_run": None,
    "next_run": "Mon Oct 12, 6:12 AM",
    "status": "active",
    "created": "Oct 9, ~5:03 PM",
    "source": "Confirmed by Don, Oct 10",
  },
  {
    "id": "primary-inbox-triage",
    "name": "Primary inbox triage",
    "owner": "Flo",
    "category": "Inbox",
    "does": "Sorts Luke's Gmail Primary inbox into 0-Grockbot Clutter, FYI, and Biz Purchase Related by standing rules. Puerto Rico urbanization mail and web forms stay in the inbox. Also emails church maintenance request alerts to Luke's personal address and two trustees.",
    "trigger": "Hourly at :15 and :45",
    "trigger_type": "Schedule",
    "delivers_to": "Luke only for church requests or decisions",
    "last_run": "Oct 10, 9:51 AM",
    "next_run": "Oct 10, 10:15 AM",
    "status": "active",
    "created": "~Sep 3",
    "source": "Confirmed by Flo, Oct 10",
  },
  {
    "id": "daily-primary-inbox-digest",
    "name": "Daily Primary inbox digest",
    "owner": "Flo",
    "category": "Inbox",
    "does": "Counts for the prior day: received, kept, Clutter, FYI, and Biz Purchase.",
    "trigger": "Weekdays 6:59 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Luke (Flo's chat)",
    "last_run": "Oct 9, 7:10 AM",
    "next_run": "Mon Oct 12, 6:59 AM",
    "status": "active",
    "created": "~Sep 11",
    "source": "Confirmed by Flo, Oct 10",
  },
  {
    "id": "remind-luke-about-randys-email",
    "name": "Remind Luke about Randy's email",
    "owner": "Flo",
    "category": "Reminders",
    "does": "One-time reminder for Oct 16, 9:07 AM if trustee Randy's email still hadn't been sent.",
    "trigger": "One-time: Oct 16, 9:07 AM",
    "trigger_type": "One-time",
    "delivers_to": "Luke (Flo's chat)",
    "last_run": None,
    "next_run": None,
    "status": "retired",
    "created": "Oct 9, ~3:55 PM",
    "source": "Confirmed by Flo, Oct 10",
  },
  {
    "id": "remind-change-dext-subscription",
    "name": "Remind: change Dext subscription",
    "owner": "CEO",
    "category": "Reminders",
    "does": "Weekdays 8:27 AM, asks Luke whether the Dext subscription change is done, and continues until he says yes.",
    "trigger": "Weekdays 8:27 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Luke (CEO chat)",
    "last_run": "Oct 9, 8:52 AM",
    "next_run": "Mon Oct 12, 8:27 AM",
    "status": "active",
    "created": "~Sep 27 (restored Oct 1)",
    "source": "Confirmed by CEO, Oct 10",
  },
  {
    "id": "remind-call-bedrock-transmission",
    "name": "Remind: call Bedrock Transmission",
    "owner": "CEO",
    "category": "Reminders",
    "does": "One-time reminder to Luke to call Bedrock Transmission.",
    "trigger": "One-time: Sep 18 at 8:00 AM",
    "trigger_type": "One-time",
    "delivers_to": "Luke (CEO chat)",
    "last_run": "Sep 18 at 8:05 AM",
    "next_run": None,
    "status": "paused",
    "created": "before Sep 18",
    "source": "Confirmed by CEO, Oct 10",
  },
  {
    "id": "daily-inventory-po-dashboard-build-backup",
    "name": "Daily Inventory PO dashboard build (backup)",
    "owner": "CEO",
    "category": "Parts & Purchasing",
    "does": "Temporary weekday 5:35 AM backup for the PO tab build. Created Oct 5 and deleted the same day once Chris's 4:05 routine was confirmed.",
    "trigger": "Weekdays 5:35 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Unknown",
    "last_run": None,
    "next_run": None,
    "status": "retired",
    "created": "Oct 5",
    "source": "Confirmed by CEO, Oct 10",
  },
  {
    "id": "remind-order-yukon-parts",
    "name": "Remind: order Yukon parts",
    "owner": "CEO",
    "category": "Reminders",
    "does": "One-time reminder to order Yukon parts. Deleted itself after firing.",
    "trigger": "One-time: Sep 17 at 8:00 AM",
    "trigger_type": "One-time",
    "delivers_to": "Luke (CEO chat)",
    "last_run": "Sep 17 at 8:04 AM",
    "next_run": None,
    "status": "retired",
    "created": "Unknown",
    "source": "Confirmed by CEO, Oct 10 (found in CEO's history files)",
  },
  {
    "id": "remind-fertilizer",
    "name": "Remind: fertilizer",
    "owner": "CEO",
    "category": "Reminders",
    "does": "One-time reminder about fertilizer. Deleted itself after firing.",
    "trigger": "One-time: Sep 17 at 8:30 AM",
    "trigger_type": "One-time",
    "delivers_to": "Luke (CEO chat)",
    "last_run": "Sep 17 at 8:51 AM",
    "next_run": None,
    "status": "retired",
    "created": "Unknown",
    "source": "Confirmed by CEO, Oct 10 (found in CEO's history files)",
  },
  {
    "id": "linkedin-weekly-drafts",
    "name": "LinkedIn weekly drafts",
    "owner": "Nathan",
    "category": "Marketing",
    "does": "Builds the week's LinkedIn post packs (personal plus company page, with photos) and emails them to luke.obx@gmail.com.",
    "trigger": "Mondays 7:58 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Luke (Nathan chat) + email to luke.obx@gmail.com",
    "last_run": "Oct 5, 8:05 AM",
    "next_run": "Oct 12, 7:58 AM",
    "status": "active",
    "created": "~Sep 3",
    "source": "Confirmed by Nathan, Oct 10",
  },
  {
    "id": "linkedin-weekly-post-check",
    "name": "LinkedIn weekly post check",
    "owner": "Nathan",
    "category": "Marketing",
    "does": "Fridays 8:13 AM, reminds Luke with the top Ready post if he hasn't posted that week.",
    "trigger": "Fridays 8:13 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Luke (Nathan chat), only if he hasn't posted",
    "last_run": "Oct 9, 8:33 AM",
    "next_run": "Oct 16, 8:13 AM",
    "status": "active",
    "created": "~Sep 9",
    "source": "Confirmed by Nathan, Oct 10",
  },
  {
    "id": "linkedin-post-day-nudge-tue-thu",
    "name": "LinkedIn post day nudge (Tue/Thu)",
    "owner": "Nathan",
    "category": "Marketing",
    "does": "Tue/Thu 8 AM nudge, replaced by the Friday check ~Sep 9.",
    "trigger": "Tue/Thu 8 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Unknown",
    "last_run": "Unknown",
    "next_run": None,
    "status": "retired",
    "created": "Unknown",
    "source": "Confirmed by Nathan, Oct 10",
  },
  {
    "id": "daily-fullbay-inventory-po-dashboard",
    "name": "Daily Fullbay Inventory PO dashboard",
    "owner": "Purchase Order Dashboard Project",
    "category": "Parts & Purchasing",
    "does": "Chris scrapes the Fullbay Needs-ordered/Order Parts vendor summary, and the bot writes the dated M-D-YY tab in the Inventory PO sheet. A Slack note to Zeb and Kent is drafted for approval.",
    "trigger": "Weekdays 4:05 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Luke (chat: vendor count, Order total, shop failures); Slack to Zeb + Kent drafted for approval",
    "last_run": "Oct 9, 4:09 AM (71 vendors, $98,077.96)",
    "next_run": "Oct 12, 4:05 AM",
    "status": "active",
    "created": "~Oct 5 (moved from Chris)",
    "source": "Confirmed by Purchase Order Dashboard Project, Oct 10",
  },
  {
    "id": "po-dashboard-4-15-blocker-check",
    "name": "PO dashboard 4:15 blocker check",
    "owner": "Purchase Order Dashboard Project",
    "category": "Parts & Purchasing",
    "does": "Alerts Luke if the day's scrape or tab is blocked or stalled.",
    "trigger": "Weekdays 4:15 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Luke, only when blocked",
    "last_run": "Oct 9, 4:20 AM",
    "next_run": "Oct 12, 4:15 AM",
    "status": "active",
    "created": "~Oct 5",
    "source": "Confirmed by Purchase Order Dashboard Project, Oct 10",
  },
  {
    "id": "fullbay-po-session-keep-alive",
    "name": "Fullbay PO session keep-alive",
    "owner": "Purchase Order Dashboard Project",
    "category": "Fullbay / Shop Ops",
    "does": "Has Chris confirm the shared Fullbay login is still signed in on Covington, and re-logs in if needed.",
    "trigger": "Weekdays 12:37 PM and 5:37 PM",
    "trigger_type": "Schedule",
    "delivers_to": "Chris; Luke only if both re-logins fail",
    "last_run": "Oct 9, 5:40 PM",
    "next_run": "Oct 12, 12:37 PM",
    "status": "active",
    "created": "~Oct 5",
    "source": "Confirmed by Purchase Order Dashboard Project, Oct 10",
  },
  {
    "id": "time-edit-state-backup-before-nightly-deploy",
    "name": "Time-edit state backup before nightly deploy",
    "owner": "Time Edit Project",
    "category": "Time & Payroll",
    "does": "Snapshots the app queue and sign-offs into the repo seed. Stopgap until the Render persistent disk is added.",
    "trigger": "Daily 2:41 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Silent unless it fails",
    "last_run": "Oct 10, 2:50 AM",
    "next_run": "Oct 11, 2:41 AM",
    "status": "active",
    "created": "~Oct 6–7",
    "source": "Confirmed by Time Edit Project, Oct 10",
  },
  {
    "id": "nightly-fullbay-clock-ins-time-edit-app",
    "name": "Nightly Fullbay clock-ins → time-edit app",
    "owner": "Time Edit Project",
    "category": "Time & Payroll",
    "does": "Chris pulls the prior day's timesheets, then a cloud agent loads them and redeploys Render.",
    "trigger": "Daily 2:56 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Luke",
    "last_run": "Oct 10, 3:05 AM",
    "next_run": "Oct 11, 2:56 AM",
    "status": "active",
    "created": "~Oct 6–7",
    "source": "Confirmed by Time Edit Project, Oct 10",
  },
  {
    "id": "morning-time-edit-ready-operations-managers",
    "name": "Morning time-edit ready → #operations-managers",
    "owner": "Time Edit Project",
    "category": "Time & Payroll",
    "does": "Posts that the utilization/time report is ready, with the link.",
    "trigger": "Daily 3:47 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Slack #operations-managers",
    "last_run": "Oct 10, 3:49 AM",
    "next_run": "Oct 11, 3:47 AM",
    "status": "active",
    "created": "~Oct 6–7",
    "source": "Confirmed by Time Edit Project, Oct 10",
  },
  {
    "id": "time-edit-restore-sign-offs-after-nightly-deploy",
    "name": "Time-edit restore sign-offs after nightly deploy",
    "owner": "Time Edit Project",
    "category": "Time & Payroll",
    "does": "Re-posts any sign-offs the redeploy dropped. Stopgap until the persistent disk.",
    "trigger": "Daily 4:23 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Silent unless it fails",
    "last_run": "Oct 10, 4:30 AM",
    "next_run": "Oct 11, 4:23 AM",
    "status": "active",
    "created": "~Oct 6–7",
    "source": "Confirmed by Time Edit Project, Oct 10",
  },
  {
    "id": "time-edit-submit-chris-applies-in-fullbay",
    "name": "Time-edit Submit → Chris applies in Fullbay",
    "owner": "Time Edit Project",
    "category": "Time & Payroll",
    "does": "When a branch manager clicks Submit in the app, Chris applies the edits in Fullbay, then the manager or Luke is notified.",
    "trigger": "Webhook from the app when a branch manager clicks Submit",
    "trigger_type": "Webhook",
    "delivers_to": "Chris, then Luke or the branch manager",
    "last_run": "Oct 9, 3:09 PM",
    "next_run": "On the next Submit",
    "status": "active",
    "created": "~Oct 6–7",
    "source": "Confirmed by Time Edit Project, Oct 10",
  },
{
    "id": "fullbay-parts-request-monitor",
    "name": "Fullbay parts-request monitor",
    "owner": "Chris",
    "category": "Parts & Purchasing",
    "does": "Checks Chris's agentmail inbox for Fullbay 'needs parts priced' alerts, opens each SO read-only, logs the Needs Quote lines, and hands new ones to Ed.",
    "trigger": "Every 5 min on weekdays, 7:01 AM–7:56 PM",
    "trigger_type": "Schedule",
    "delivers_to": "Ed (Luke only if blocked)",
    "last_run": "Oct 9, 7:59 PM",
    "next_run": "Mon Oct 12, 7:01 AM",
    "status": "active",
    "created": "~Sep 22",
    "source": "Confirmed by Chris, Oct 10",
  },
  {
    "id": "fullbay-parts-research-accuracy",
    "name": "Fullbay parts research accuracy",
    "owner": "Chris",
    "category": "Parts & Purchasing",
    "does": "Syncs Fullbay order status and scores Ed's researched part numbers against what was actually ordered.",
    "trigger": "Hourly on weekdays, 7:24 AM–7:24 PM",
    "trigger_type": "Schedule",
    "delivers_to": "Ed (quiet if nothing new)",
    "last_run": "Oct 9, 7:26 PM",
    "next_run": "Oct 12, 7:24 AM",
    "status": "active",
    "created": "~Sep 22–23",
    "source": "Confirmed by Chris, Oct 10",
  },
  {
    "id": "servco-2-0-daily-inventory-download",
    "name": "Servco 2.0 daily inventory download",
    "owner": "Chris",
    "category": "Parts & Purchasing",
    "does": "Grabs the nightly Fullbay inventory xlsx as the parts-research source of truth.",
    "trigger": "Weekdays 4:58 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Silent unless it fails",
    "last_run": "Oct 9, 5:03 AM",
    "next_run": "Oct 12, 4:58 AM",
    "status": "active",
    "created": "before Sep 24",
    "source": "Confirmed by Chris, Oct 10",
    "flag": "Possible duplicate: Chris 4:58 and 2.0 4:59 both pull the inventory file",
  },
  {
    "id": "fullbay-parts-alert-instant",
    "name": "Fullbay parts alert instant",
    "owner": "Chris",
    "category": "Parts & Purchasing",
    "does": "Webhook-triggered version of the parts monitor.",
    "trigger": "Webhook",
    "trigger_type": "Webhook",
    "delivers_to": "Ed",
    "last_run": None,
    "next_run": None,
    "status": "active",
    "created": "~Sep 22",
    "source": "Confirmed by Chris, Oct 10",
  },
  {
    "id": "daily-fullbay-inventory-po-dashboard-chris",
    "name": "Daily Fullbay Inventory PO dashboard (Chris's original)",
    "owner": "Chris",
    "category": "Parts & Purchasing",
    "does": "Weekdays 4:05 AM, Needs ordered → Order Parts scrape into a dated tab. Ownership moved to Purchase Order Dashboard Project on Oct 5.",
    "trigger": "Weekdays 4:05 AM",
    "trigger_type": "Schedule",
    "delivers_to": "Luke",
    "last_run": "Oct 5, 4:05 AM",
    "next_run": None,
    "status": "paused",
    "created": "Sep 25",
    "source": "Confirmed by Chris, Oct 10",
  },
  {
    "id": "fullbay-session-keep-alive-chris",
    "name": "Fullbay session keep-alive (Chris's original)",
    "owner": "Chris",
    "category": "Fullbay / Shop Ops",
    "does": "Checks the login and that the shop is Covington. Replaced by PO Dashboard Project's keep-alive.",
    "trigger": "Weekdays 12:37 PM and 5:37 PM",
    "trigger_type": "Schedule",
    "delivers_to": "Unknown",
    "last_run": None,
    "next_run": None,
    "status": "paused",
    "created": "~Oct 5",
    "source": "Confirmed by Chris, Oct 10",
  },
]
